server {
    server_name labmattos.com.br www.labmattos.com.br;

    root /var/www/site-mattos;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/labmattos.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/labmattos.com.br/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = www.labmattos.com.br) {
        return 301 https://$host$request_uri;
    }

    if ($host = labmattos.com.br) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;
    server_name labmattos.com.br www.labmattos.com.br;
    return 404;
}
